# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\repos\nnacs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\repos\nnacs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\repos\nnacs\CMakeFiles D:\repos\nnacs\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\repos\nnacs\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix

# Build rule for target.
matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 matrix
.PHONY : matrix

# fast build rule for target.
matrix/fast:
	$(MAKE) -f Matrix.041\CMakeFiles\matrix.dir\build.make Matrix.041/CMakeFiles/matrix.dir/build
.PHONY : matrix/fast

#=============================================================================
# Target rules for targets named pnna

# Build rule for target.
pnna: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 pnna
.PHONY : pnna

# fast build rule for target.
pnna/fast:
	$(MAKE) -f NeuArch\CMakeFiles\pnna.dir\build.make NeuArch/CMakeFiles/pnna.dir/build
.PHONY : pnna/fast

#=============================================================================
# Target rules for targets named test_vsscanf

# Build rule for target.
test_vsscanf: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_vsscanf
.PHONY : test_vsscanf

# fast build rule for target.
test_vsscanf/fast:
	$(MAKE) -f NeuArch\CMakeFiles\test_vsscanf.dir\build.make NeuArch/CMakeFiles/test_vsscanf.dir/build
.PHONY : test_vsscanf/fast

#=============================================================================
# Target rules for targets named Distr1D

# Build rule for target.
Distr1D: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Distr1D
.PHONY : Distr1D

# fast build rule for target.
Distr1D/fast:
	$(MAKE) -f NaTools\CMakeFiles\Distr1D.dir\build.make NaTools/CMakeFiles/Distr1D.dir/build
.PHONY : Distr1D/fast

#=============================================================================
# Target rules for targets named Distr2D

# Build rule for target.
Distr2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Distr2D
.PHONY : Distr2D

# fast build rule for target.
Distr2D/fast:
	$(MAKE) -f NaTools\CMakeFiles\Distr2D.dir\build.make NaTools/CMakeFiles/Distr2D.dir/build
.PHONY : Distr2D/fast

#=============================================================================
# Target rules for targets named EvalNN

# Build rule for target.
EvalNN: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 EvalNN
.PHONY : EvalNN

# fast build rule for target.
EvalNN/fast:
	$(MAKE) -f NaTools\CMakeFiles\EvalNN.dir\build.make NaTools/CMakeFiles/EvalNN.dir/build
.PHONY : EvalNN/fast

#=============================================================================
# Target rules for targets named FileCvt

# Build rule for target.
FileCvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 FileCvt
.PHONY : FileCvt

# fast build rule for target.
FileCvt/fast:
	$(MAKE) -f NaTools\CMakeFiles\FileCvt.dir\build.make NaTools/CMakeFiles/FileCvt.dir/build
.PHONY : FileCvt/fast

#=============================================================================
# Target rules for targets named MakeNN

# Build rule for target.
MakeNN: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 MakeNN
.PHONY : MakeNN

# fast build rule for target.
MakeNN/fast:
	$(MAKE) -f NaTools\CMakeFiles\MakeNN.dir\build.make NaTools/CMakeFiles/MakeNN.dir/build
.PHONY : MakeNN/fast

#=============================================================================
# Target rules for targets named ResetNN

# Build rule for target.
ResetNN: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ResetNN
.PHONY : ResetNN

# fast build rule for target.
ResetNN/fast:
	$(MAKE) -f NaTools\CMakeFiles\ResetNN.dir\build.make NaTools/CMakeFiles/ResetNN.dir/build
.PHONY : ResetNN/fast

#=============================================================================
# Target rules for targets named StatAn

# Build rule for target.
StatAn: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 StatAn
.PHONY : StatAn

# fast build rule for target.
StatAn/fast:
	$(MAKE) -f NaTools\CMakeFiles\StatAn.dir\build.make NaTools/CMakeFiles/StatAn.dir/build
.PHONY : StatAn/fast

#=============================================================================
# Target rules for targets named TrainNN

# Build rule for target.
TrainNN: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TrainNN
.PHONY : TrainNN

# fast build rule for target.
TrainNN/fast:
	$(MAKE) -f NaTools\CMakeFiles\TrainNN.dir\build.make NaTools/CMakeFiles/TrainNN.dir/build
.PHONY : TrainNN/fast

#=============================================================================
# Target rules for targets named UNGen

# Build rule for target.
UNGen: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 UNGen
.PHONY : UNGen

# fast build rule for target.
UNGen/fast:
	$(MAKE) -f NaTools\CMakeFiles\UNGen.dir\build.make NaTools/CMakeFiles/UNGen.dir/build
.PHONY : UNGen/fast

#=============================================================================
# Target rules for targets named d2ts

# Build rule for target.
d2ts: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 d2ts
.PHONY : d2ts

# fast build rule for target.
d2ts/fast:
	$(MAKE) -f dtools\CMakeFiles\d2ts.dir\build.make dtools/CMakeFiles/d2ts.dir/build
.PHONY : d2ts/fast

#=============================================================================
# Target rules for targets named dconst

# Build rule for target.
dconst: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dconst
.PHONY : dconst

# fast build rule for target.
dconst/fast:
	$(MAKE) -f dtools\CMakeFiles\dconst.dir\build.make dtools/CMakeFiles/dconst.dir/build
.PHONY : dconst/fast

#=============================================================================
# Target rules for targets named dcorr

# Build rule for target.
dcorr: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dcorr
.PHONY : dcorr

# fast build rule for target.
dcorr/fast:
	$(MAKE) -f dtools\CMakeFiles\dcorr.dir\build.make dtools/CMakeFiles/dcorr.dir/build
.PHONY : dcorr/fast

#=============================================================================
# Target rules for targets named djacob

# Build rule for target.
djacob: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 djacob
.PHONY : djacob

# fast build rule for target.
djacob/fast:
	$(MAKE) -f dtools\CMakeFiles\djacob.dir\build.make dtools/CMakeFiles/djacob.dir/build
.PHONY : djacob/fast

#=============================================================================
# Target rules for targets named dmean

# Build rule for target.
dmean: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dmean
.PHONY : dmean

# fast build rule for target.
dmean/fast:
	$(MAKE) -f dtools\CMakeFiles\dmean.dir\build.make dtools/CMakeFiles/dmean.dir/build
.PHONY : dmean/fast

#=============================================================================
# Target rules for targets named dmeander

# Build rule for target.
dmeander: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dmeander
.PHONY : dmeander

# fast build rule for target.
dmeander/fast:
	$(MAKE) -f dtools\CMakeFiles\dmeander.dir\build.make dtools/CMakeFiles/dmeander.dir/build
.PHONY : dmeander/fast

#=============================================================================
# Target rules for targets named dmse

# Build rule for target.
dmse: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dmse
.PHONY : dmse

# fast build rule for target.
dmse/fast:
	$(MAKE) -f dtools\CMakeFiles\dmse.dir\build.make dtools/CMakeFiles/dmse.dir/build
.PHONY : dmse/fast

#=============================================================================
# Target rules for targets named dmult

# Build rule for target.
dmult: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dmult
.PHONY : dmult

# fast build rule for target.
dmult/fast:
	$(MAKE) -f dtools\CMakeFiles\dmult.dir\build.make dtools/CMakeFiles/dmult.dir/build
.PHONY : dmult/fast

#=============================================================================
# Target rules for targets named drand

# Build rule for target.
drand: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 drand
.PHONY : drand

# fast build rule for target.
drand/fast:
	$(MAKE) -f dtools\CMakeFiles\drand.dir\build.make dtools/CMakeFiles/drand.dir/build
.PHONY : drand/fast

#=============================================================================
# Target rules for targets named drandmea

# Build rule for target.
drandmea: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 drandmea
.PHONY : drandmea

# fast build rule for target.
drandmea/fast:
	$(MAKE) -f dtools\CMakeFiles\drandmea.dir\build.make dtools/CMakeFiles/drandmea.dir/build
.PHONY : drandmea/fast

#=============================================================================
# Target rules for targets named dranduni

# Build rule for target.
dranduni: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dranduni
.PHONY : dranduni

# fast build rule for target.
dranduni/fast:
	$(MAKE) -f dtools\CMakeFiles\dranduni.dir\build.make dtools/CMakeFiles/dranduni.dir/build
.PHONY : dranduni/fast

#=============================================================================
# Target rules for targets named dsin

# Build rule for target.
dsin: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dsin
.PHONY : dsin

# fast build rule for target.
dsin/fast:
	$(MAKE) -f dtools\CMakeFiles\dsin.dir\build.make dtools/CMakeFiles/dsin.dir/build
.PHONY : dsin/fast

#=============================================================================
# Target rules for targets named dsmooth

# Build rule for target.
dsmooth: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dsmooth
.PHONY : dsmooth

# fast build rule for target.
dsmooth/fast:
	$(MAKE) -f dtools\CMakeFiles\dsmooth.dir\build.make dtools/CMakeFiles/dsmooth.dir/build
.PHONY : dsmooth/fast

#=============================================================================
# Target rules for targets named dstat

# Build rule for target.
dstat: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dstat
.PHONY : dstat

# fast build rule for target.
dstat/fast:
	$(MAKE) -f dtools\CMakeFiles\dstat.dir\build.make dtools/CMakeFiles/dstat.dir/build
.PHONY : dstat/fast

#=============================================================================
# Target rules for targets named dstatsb

# Build rule for target.
dstatsb: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dstatsb
.PHONY : dstatsb

# fast build rule for target.
dstatsb/fast:
	$(MAKE) -f dtools\CMakeFiles\dstatsb.dir\build.make dtools/CMakeFiles/dstatsb.dir/build
.PHONY : dstatsb/fast

#=============================================================================
# Target rules for targets named dstddev

# Build rule for target.
dstddev: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dstddev
.PHONY : dstddev

# fast build rule for target.
dstddev/fast:
	$(MAKE) -f dtools\CMakeFiles\dstddev.dir\build.make dtools/CMakeFiles/dstddev.dir/build
.PHONY : dstddev/fast

#=============================================================================
# Target rules for targets named dsteps

# Build rule for target.
dsteps: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dsteps
.PHONY : dsteps

# fast build rule for target.
dsteps/fast:
	$(MAKE) -f dtools\CMakeFiles\dsteps.dir\build.make dtools/CMakeFiles/dsteps.dir/build
.PHONY : dsteps/fast

#=============================================================================
# Target rules for targets named dsub

# Build rule for target.
dsub: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dsub
.PHONY : dsub

# fast build rule for target.
dsub/fast:
	$(MAKE) -f dtools\CMakeFiles\dsub.dir\build.make dtools/CMakeFiles/dsub.dir/build
.PHONY : dsub/fast

#=============================================================================
# Target rules for targets named dsum

# Build rule for target.
dsum: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dsum
.PHONY : dsum

# fast build rule for target.
dsum/fast:
	$(MAKE) -f dtools\CMakeFiles\dsum.dir\build.make dtools/CMakeFiles/dsum.dir/build
.PHONY : dsum/fast

#=============================================================================
# Target rules for targets named dtf

# Build rule for target.
dtf: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dtf
.PHONY : dtf

# fast build rule for target.
dtf/fast:
	$(MAKE) -f dtools\CMakeFiles\dtf.dir\build.make dtools/CMakeFiles/dtf.dir/build
.PHONY : dtf/fast

#=============================================================================
# Target rules for targets named dwtest

# Build rule for target.
dwtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dwtest
.PHONY : dwtest

# fast build rule for target.
dwtest/fast:
	$(MAKE) -f dtools\CMakeFiles\dwtest.dir\build.make dtools/CMakeFiles/dwtest.dir/build
.PHONY : dwtest/fast

#=============================================================================
# Target rules for targets named dwtest2

# Build rule for target.
dwtest2: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dwtest2
.PHONY : dwtest2

# fast build rule for target.
dwtest2/fast:
	$(MAKE) -f dtools\CMakeFiles\dwtest2.dir\build.make dtools/CMakeFiles/dwtest2.dir/build
.PHONY : dwtest2/fast

#=============================================================================
# Target rules for targets named dcsloop

# Build rule for target.
dcsloop: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dcsloop
.PHONY : dcsloop

# fast build rule for target.
dcsloop/fast:
	$(MAKE) -f dcsloop\CMakeFiles\dcsloop.dir\build.make dcsloop/CMakeFiles/dcsloop.dir/build
.PHONY : dcsloop/fast

#=============================================================================
# Target rules for targets named dnnplant

# Build rule for target.
dnnplant: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dnnplant
.PHONY : dnnplant

# fast build rule for target.
dnnplant/fast:
	$(MAKE) -f dplantid\CMakeFiles\dnnplant.dir\build.make dplantid/CMakeFiles/dnnplant.dir/build
.PHONY : dnnplant/fast

#=============================================================================
# Target rules for targets named dplantid

# Build rule for target.
dplantid: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dplantid
.PHONY : dplantid

# fast build rule for target.
dplantid/fast:
	$(MAKE) -f dplantid\CMakeFiles\dplantid.dir\build.make dplantid/CMakeFiles/dplantid.dir/build
.PHONY : dplantid/fast

#=============================================================================
# Target rules for targets named dcontrp

# Build rule for target.
dcontrp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dcontrp
.PHONY : dcontrp

# fast build rule for target.
dcontrp/fast:
	$(MAKE) -f dcontrp\CMakeFiles\dcontrp.dir\build.make dcontrp/CMakeFiles/dcontrp.dir/build
.PHONY : dcontrp/fast

#=============================================================================
# Target rules for targets named dcontrf

# Build rule for target.
dcontrf: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 dcontrf
.PHONY : dcontrf

# fast build rule for target.
dcontrf/fast:
	$(MAKE) -f dcontrf\CMakeFiles\dcontrf.dir\build.make dcontrf/CMakeFiles/dcontrf.dir/build
.PHONY : dcontrf/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... matrix
	@echo ... pnna
	@echo ... test_vsscanf
	@echo ... Distr1D
	@echo ... Distr2D
	@echo ... EvalNN
	@echo ... FileCvt
	@echo ... MakeNN
	@echo ... ResetNN
	@echo ... StatAn
	@echo ... TrainNN
	@echo ... UNGen
	@echo ... d2ts
	@echo ... dconst
	@echo ... dcorr
	@echo ... djacob
	@echo ... dmean
	@echo ... dmeander
	@echo ... dmse
	@echo ... dmult
	@echo ... drand
	@echo ... drandmea
	@echo ... dranduni
	@echo ... dsin
	@echo ... dsmooth
	@echo ... dstat
	@echo ... dstatsb
	@echo ... dstddev
	@echo ... dsteps
	@echo ... dsub
	@echo ... dsum
	@echo ... dtf
	@echo ... dwtest
	@echo ... dwtest2
	@echo ... dcsloop
	@echo ... dnnplant
	@echo ... dplantid
	@echo ... dcontrp
	@echo ... dcontrf
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

